package com.newrizer.arcade.crypto

import android.content.Context
import android.util.Base64
import com.google.crypto.tink.HybridDecrypt
import com.google.crypto.tink.HybridEncrypt
import com.google.crypto.tink.KeyTemplates
import com.google.crypto.tink.KeysetHandle
import com.google.crypto.tink.TinkProtoKeysetFormat
import com.google.crypto.tink.hybrid.HybridConfig
import com.google.crypto.tink.integration.android.AndroidKeysetManager
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * End-to-end encryption primitives.
 *
 * Layers:
 *  1. Device identity - an HPKE (X25519 + HKDF-SHA256 + AES-256-GCM) key pair.
 *     The private keyset is sealed by an Android Keystore master key and never
 *     leaves the device.
 *  2. Room key - 32 random bytes generated by the host, wrapped once per member
 *     with that member's public key. The server relays ciphertext only.
 *  3. Payloads - chat and any metadata are sealed with AES-256-GCM under the
 *     room key; LiveKit media frames use the same room key through its own
 *     key provider.
 */
object E2EE {

    private const val PREF_FILE = "arcade_keyset"
    private const val KEYSET_NAME = "device_identity"
    private const val MASTER_KEY_URI = "android-keystore://arcade_master_key"
    private const val GCM_TAG_BITS = 128
    private const val GCM_NONCE_BYTES = 12

    private val random = SecureRandom()

    @Volatile
    private var handle: KeysetHandle? = null

    fun initialise(context: Context) {
        if (handle != null) return
        synchronized(this) {
            if (handle != null) return
            HybridConfig.register()
            handle = AndroidKeysetManager.Builder()
                .withSharedPref(context.applicationContext, KEYSET_NAME, PREF_FILE)
                .withKeyTemplate(KeyTemplates.get("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW"))
                .withMasterKeyUri(MASTER_KEY_URI)
                .build()
                .keysetHandle
        }
    }

    private fun requireHandle(): KeysetHandle =
        handle ?: error("E2EE.initialise must run before any key operation")

    /** Serialised public keyset, safe to publish. */
    fun publicKeyBase64(): String {
        val serialised = TinkProtoKeysetFormat.serializeKeysetWithoutSecret(
            requireHandle().publicKeysetHandle,
        )
        return Base64.encodeToString(serialised, Base64.NO_WRAP)
    }

    /** Stable 128-bit fingerprint of the public key, used as keyId. */
    fun publicKeyId(): String = fingerprint(publicKeyBase64())

    fun fingerprint(publicKeyBase64: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(Base64.decode(publicKeyBase64, Base64.NO_WRAP))
        return digest.take(16).joinToString("") { "%02x".format(it) }
    }

    fun newRoomKey(): ByteArray = ByteArray(32).also(random::nextBytes)

    /** Wraps a room key for one recipient. Only that recipient can open it. */
    fun wrapRoomKey(roomKey: ByteArray, recipientPublicKeyBase64: String, context: ByteArray): String {
        val recipient = TinkProtoKeysetFormat.parseKeysetWithoutSecret(
            Base64.decode(recipientPublicKeyBase64, Base64.NO_WRAP),
        )
        val encrypter = recipient.getPrimitive(HybridEncrypt::class.java)
        return Base64.encodeToString(encrypter.encrypt(roomKey, context), Base64.NO_WRAP)
    }

    fun unwrapRoomKey(wrappedBase64: String, context: ByteArray): ByteArray {
        val decrypter = requireHandle().getPrimitive(HybridDecrypt::class.java)
        return decrypter.decrypt(Base64.decode(wrappedBase64, Base64.NO_WRAP), context)
    }

    /** AES-256-GCM seal. Returns ciphertext and nonce, both base64. */
    fun seal(roomKey: ByteArray, plaintext: ByteArray, aad: ByteArray): Pair<String, String> {
        require(roomKey.size == 32) { "room key must be 32 bytes" }
        val nonce = ByteArray(GCM_NONCE_BYTES).also(random::nextBytes)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.ENCRYPT_MODE,
            SecretKeySpec(roomKey, "AES"),
            GCMParameterSpec(GCM_TAG_BITS, nonce),
        )
        cipher.updateAAD(aad)
        val sealed = cipher.doFinal(plaintext)
        return Base64.encodeToString(sealed, Base64.NO_WRAP) to
            Base64.encodeToString(nonce, Base64.NO_WRAP)
    }

    fun open(roomKey: ByteArray, ciphertextBase64: String, nonceBase64: String, aad: ByteArray): ByteArray {
        require(roomKey.size == 32) { "room key must be 32 bytes" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            SecretKeySpec(roomKey, "AES"),
            GCMParameterSpec(GCM_TAG_BITS, Base64.decode(nonceBase64, Base64.NO_WRAP)),
        )
        cipher.updateAAD(aad)
        return cipher.doFinal(Base64.decode(ciphertextBase64, Base64.NO_WRAP))
    }

    fun encodeKey(roomKey: ByteArray): String = Base64.encodeToString(roomKey, Base64.NO_WRAP)

    /** Overwrites key bytes once they are no longer needed. */
    fun wipe(bytes: ByteArray?) {
        if (bytes != null) java.util.Arrays.fill(bytes, 0)
    }
}
