apiBaseUrl=https://omletarcade-newrizer-slavamem31yt-org-1.onrender.com
firebaseApiKey=AIzaSyAgs7JCF5DPjyt59eY5Ii_u5tTBXcyZnIQ
firebaseAppId=1:659141695366:android:a4f982f755263f751e3e07
firebaseProjectId=omletarcade-790f7
firebaseDbUrl=https://omletarcade-790f7-default-rtdb.europe-west1.firebasedatabase.app
firebaseSenderId=659141695366
firebaseStorageBucket=omletarcade-790f7.firebasestorage.app
appCheckToken=7Gl6rxNIjBpwXFQB2Q5S7N23kayXVgjWWFvvInUP
releaseStoreFile=keystore/release.jks
releaseStorePassword=arcade-release-7Gl6rxNIjBpwXFQB2Q5S7N23kayXVgjWWFvvInUP
releaseKeyAlias=arcade
releaseKeyPassword=arcade-release-7Gl6rxNIjBpwXFQB2Q5S7N23kayXVgjWWFvvInUP
