'use strict';
/**
 * LiveKit integration.
 *
 * The API key and secret are read from the environment and used in exactly two
 * places: minting a room-scoped access token, and verifying an incoming
 * webhook signature. Neither value is ever returned to a client, written to a
 * log, or embedded in a static asset.
 */
const { AccessToken, WebhookReceiver } = require('livekit-server-sdk');
const { config } = require('../config');
const logger = require('../logger');

let receiver = null;
function webhookReceiver() {
  if (!receiver) receiver = new WebhookReceiver(config.livekit.apiKey, config.livekit.apiSecret);
  return receiver;
}

/**
 * Room names are namespaced by kind so a party, a call, a Minecraft crew and a
 * broadcast can never collide, and so a token minted for one cannot be replayed
 * into another.
 */
const roomName = {
  party: (partyId) => `party-${partyId}`,
  call: (callId) => `call-${callId}`,
  minecraft: (serverId) => `mc-${serverId}`,
  broadcast: (broadcastId) => `bc-${broadcastId}`,
};

/**
 * @param {object} opts
 * @param {number} opts.userId      numeric user id (becomes the identity)
 * @param {string} opts.username    display identity in the room
 * @param {string} opts.room        room name, must already be namespaced
 * @param {boolean} opts.canPublish host/streamer true, listener false
 * @param {boolean} opts.canSubscribe
 * @param {object} [opts.metadata]  small, non-sensitive payload for other clients
 */
async function issueToken({ userId, username, room, canPublish = true, canSubscribe = true, metadata = {} }) {
  if (!config.livekit.apiKey || !config.livekit.apiSecret) {
    throw new Error('LiveKit credentials are not configured on this server');
  }
  // A room name is generated by this server, but it is still matched against a
  // strict shape: it becomes part of a LiveKit grant, so anything unexpected is
  // refused rather than normalized.
  if (!room || typeof room !== 'string' || !/^[A-Za-z0-9-]{1,64}$/.test(room)) {
    throw new Error(`refusing to mint a token for room "${room}"`);
  }
  const identity = `u${userId}`;
  const token = new AccessToken(config.livekit.apiKey, config.livekit.apiSecret, {
    identity,
    name: String(username).slice(0, 32),
    ttl: `${config.livekit.tokenTtlSeconds}s`,
    metadata: JSON.stringify(metadata).slice(0, 512),
  });
  token.addGrant({
    room,
    roomJoin: true,
    canPublish,
    canSubscribe,
    canPublishData: true,
    canUpdateOwnMetadata: true,
    hidden: false,
    recorder: false,
  });
  return {
    token: await token.toJwt(),
    url: config.livekit.url,
    room,
    identity,
    expiresInSeconds: config.livekit.tokenTtlSeconds,
  };
}

/** Verify a webhook body. Throws on a bad signature (caller returns 401). */
function receiveWebhook(body, authHeader) {
  return webhookReceiver().receive(body, authHeader);
}

function assertConfigured() {
  const missing = [];
  if (!config.livekit.url) missing.push('LIVEKIT_URL');
  if (!config.livekit.apiKey) missing.push('LIVEKIT_API_KEY');
  if (!config.livekit.apiSecret) missing.push('LIVEKIT_API_SECRET');
  if (missing.length) {
    logger.error('livekit not configured', { missing });
    return false;
  }
  return true;
}

module.exports = { issueToken, receiveWebhook, roomName, assertConfigured };
