'use strict';
/**
 * Minecraft host pack contents.
 *
 * Text only, generated per request. The pack is what a host runs on their own
 * machine: a hardened server config, a crash watchdog, connection-rate
 * firewall rules and a fail2ban jail. Nothing in it phones home, and this
 * server never executes any of it.
 */
const { config } = require('../config');

function bedrockProperties({ name, motd, maxPlayers, port }) {
  return `# Generated by Omlet Arcade. Safe to edit; keep the port in sync with the app.
server-name=${name}
gamemode=survival
difficulty=normal
allow-cheats=false
max-players=${maxPlayers}
online-mode=true
allow-list=true
server-port=${port}
server-portv6=${port}
enable-lan-visibility=false
view-distance=8
tick-distance=4
player-idle-timeout=30
max-threads=4
level-name=world
level-seed=
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=true
compression-threshold=1
compression-algorithm=zlib
server-authoritative-movement=server-auth
player-movement-score-threshold=20
player-movement-action-direction-threshold=0.85
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
correct-player-movement=false
server-authoritative-block-breaking=false
chat-restriction=None
disable-player-interaction=false
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-persona=false
disable-custom-skins=false
emote-chat-restriction=None
`;
}

function javaProperties({ name, motd, maxPlayers, port }) {
  return `# Generated by Omlet Arcade.
server-name=${name}
motd=${motd}
server-port=${port}
max-players=${maxPlayers}
online-mode=true
white-list=true
enforce-whitelist=true
view-distance=8
simulation-distance=6
spawn-protection=16
allow-nether=true
pvp=true
difficulty=normal
gamemode=survival
network-compression-threshold=256
max-tick-time=60000
enable-query=false
enable-rcon=false
enable-status=false
sync-chunk-writes=true
entity-broadcast-range-percentage=60
rate-limit=64
`;
}

const START_BEDROCK = `#!/usr/bin/env bash
# Start the Bedrock dedicated server under a watchdog. Idempotent.
set -euo pipefail
cd "$(dirname "$0")"
BIN=./bedrock_server
[ -x "$BIN" ] || { echo "Download the Bedrock dedicated server into this folder first (see README.md)."; exit 1; }
mkdir -p logs
if [ -f server.pid ] && kill -0 "$(cat server.pid)" 2>/dev/null; then
  echo "Already running (pid $(cat server.pid))."; exit 0
fi
LD_LIBRARY_PATH=. nohup "$BIN" >> "logs/server-$(date +%Y%m%d-%H%M%S).log" 2>&1 &
echo $! > server.pid
echo "Started with pid $(cat server.pid)."
echo "Now set the server status to Running in the app so your friends can see it."
`;

const START_JAVA = `#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
JAR=$(ls -1 *.jar 2>/dev/null | grep -v -e '^libraries$' | head -n1 || true)
[ -n "$JAR" ] || { echo "Put the server jar in this folder first (see README.md)."; exit 1; }
mkdir -p logs
if [ -f server.pid ] && kill -0 "$(cat server.pid)" 2>/dev/null; then
  echo "Already running (pid $(cat server.pid))."; exit 0
fi
nohup java -Xms1G -Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 \\
  -jar "$JAR" nogui >> "logs/server-$(date +%Y%m%d-%H%M%S).log" 2>&1 &
echo $! > server.pid
echo "Started with pid $(cat server.pid)."
`;

const STOP = `#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
[ -f server.pid ] || { echo "Not running."; exit 0; }
PID=$(cat server.pid)
if kill -0 "$PID" 2>/dev/null; then
  kill -TERM "$PID"
  for _ in $(seq 1 30); do kill -0 "$PID" 2>/dev/null || break; sleep 1; done
  kill -0 "$PID" 2>/dev/null && kill -KILL "$PID" || true
  echo "Stopped."
else
  echo "Stale pid file."
fi
rm -f server.pid
`;

const WATCHDOG = `#!/usr/bin/env bash
# Restarts the server when it dies, with backoff so a crash loop cannot spin.
set -uo pipefail
cd "$(dirname "$0")"
MAX_RESTARTS=5
WINDOW=600
declare -a TIMES=()
while true; do
  if [ -f server.pid ] && kill -0 "$(cat server.pid)" 2>/dev/null; then
    sleep 10; continue
  fi
  NOW=$(date +%s)
  TIMES+=("$NOW")
  TIMES=($(for t in "\${TIMES[@]}"; do [ $((NOW - t)) -lt $WINDOW ] && echo "$t"; done))
  if [ "\${#TIMES[@]}" -ge $MAX_RESTARTS ]; then
    echo "[$(date -Is)] $MAX_RESTARTS crashes in \${WINDOW}s: giving up. Check logs/." >&2
    exit 1
  fi
  echo "[$(date -Is)] server down, restarting (attempt \${#TIMES[@]}/$MAX_RESTARTS)"
  ./start.sh || true
  sleep 15
done
`;

const FIREWALL = `#!/usr/bin/env bash
# Connection-rate rules for a game host. Run once as root: sudo ./iptables.rules
# The CONNLIMIT and HASHLIMIT rules are what stops a single flood from taking
# the box down; they cap new connections per source instead of banning it.
set -euo pipefail
GAME_PORT=__PORT__          # UDP for Bedrock, TCP for Java
GAME_PROTO=__PROTO__
SSH_PORT=22

iptables -N OMLET_GAME 2>/dev/null || iptables -F OMLET_GAME

# Drop packets that belong to no connection.
iptables -A OMLET_GAME -m conntrack --ctstate INVALID -j DROP
# Never more than 12 concurrent connections from one source.
iptables -A OMLET_GAME -m connlimit --connlimit-above 12 --connlimit-mask 32 -j DROP
# Never more than 20 new connections per minute from one source.
iptables -A OMLET_GAME -m hashlimit --hashlimit-name game --hashlimit-above 20/min \\
  --hashlimit-burst 8 --hashlimit-mode srcip -j DROP
# Global new-connection ceiling so the box stays reachable.
iptables -A OMLET_GAME -m conntrack --ctstate NEW -m limit --limit 60/s --limit-burst 120 -j ACCEPT
iptables -A OMLET_GAME -j DROP

iptables -C INPUT -p __PROTO__ --dport $GAME_PORT -j OMLET_GAME 2>/dev/null || \\
  iptables -I INPUT -p __PROTO__ --dport $GAME_PORT -j OMLET_GAME

# Keep SSH alive and rate limited.
iptables -C INPUT -p tcp --dport $SSH_PORT -m conntrack --ctstate NEW -m limit --limit 5/min --limit-burst 10 -j ACCEPT 2>/dev/null || \\
  iptables -I INPUT -p tcp --dport $SSH_PORT -m conntrack --ctstate NEW -m limit --limit 5/min --limit-burst 10 -j ACCEPT

# Persist across reboots (Debian/Ubuntu: apt install iptables-persistent).
command -v netfilter-persist >/dev/null 2>&1 && netfilter-persist save || \\
  echo "Install iptables-persistent to keep these rules across reboots."
echo "Rules applied for $GAME_PROTO/$GAME_PORT."
`;

const FAIL2BAN = `# /etc/fail2ban/jail.d/omlet-game.conf
# Bans sources that keep hammering the game port after the firewall drops them.
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 20
backend  = systemd

[omlet-game]
enabled  = true
port     = __PORT__
protocol = __PROTO__
filter   = omlet-game
logpath  = /var/log/kern.log
action   = iptables-allports[name=omlet-game]
`;

const SYSTEMD = `[Unit]
Description=Omlet Arcade Minecraft host
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=minecraft
WorkingDirectory=/opt/minecraft
ExecStart=/opt/minecraft/watchdog.sh
Restart=on-failure
RestartSec=10
# Keep a runaway server from taking the host with it.
MemoryMax=4G
CPUQuota=300%
TasksMax=512
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true

[Install]
WantedBy=multi-user.target
`;

const WHITELIST = `[]
`;

const PERMISSIONS = `{
  "values": []
}
`;

function readme({ name, motd, maxPlayers, port, edition }) {
  const proto = edition === 'java' ? 'tcp' : 'udp';
  return `# ${name} — host pack

Generated by Omlet Arcade. This pack configures a ${edition === 'java' ? 'Java' : 'Bedrock'} dedicated
server and hardens the machine it runs on. The app never runs the game for you:
you run it here, then set the server to Running in the app so your friends see
the address and the voice room.

## 1. Get the server binary

${edition === 'java'
    ? 'Download the official server jar from minecraft.net and drop it in this folder.'
    : 'Download the Bedrock Dedicated Server archive from minecraft.net, unpack it into\nthis folder so `bedrock_server` sits next to `start.sh`, then `chmod +x bedrock_server`.'}

## 2. Configure

- \`server.properties\` is pre-filled: name "${name}", port ${port}, ${maxPlayers} players.
- \`allow-list=true\` is on. Add your friends in the app (or edit whitelist.json),
  not by turning the allow-list off — an open list is how strangers join.

## 3. Harden the machine

    sudo ./iptables.rules

That caps new connections per source (${proto}/${port}) so one flood cannot take the box down.
Optional but recommended:

    sudo cp fail2ban-jail.conf /etc/fail2ban/jail.d/omlet-game.conf
    sudo systemctl restart fail2ban

## 4. Run

    chmod +x start.sh stop.sh watchdog.sh
    ./start.sh

\`watchdog.sh\` restarts the server if it dies, and gives up after 5 crashes in
10 minutes instead of spinning forever. To run it as a service:

    sudo useradd -r -d /opt/minecraft minecraft
    sudo cp -r . /opt/minecraft && sudo chown -R minecraft:minecraft /opt/minecraft
    sudo cp omlet-minecraft.service /etc/systemd/system/
    sudo systemctl enable --now omlet-minecraft

## 5. Tell the app

In Omlet Arcade: Minecraft > your server > set status to Running. Your friends
get the address (\`<your-public-ip>:${port}\`) and a voice room that stays open
while they play.

## Troubleshooting

- Port not reachable: open ${proto}/${port} in the cloud firewall too, not only here.
- Behind NAT: forward ${proto}/${port} to this machine, or rent a small VPS.
- Voice but no game: the voice room uses the app's own transport, it does not
  depend on this server being reachable.
- MOTD shows as "${motd}".

## What this pack never does

It sends no telemetry, opens no inbound port besides ${proto}/${port} and SSH,
and stores no credentials. Voice runs through the app, not through this box.
`;
}

function build({ name, motd, maxPlayers, port, edition }) {
  const proto = edition === 'java' ? 'tcp' : 'udp';
  const firewall = FIREWALL.replace(/__PORT__/g, String(port)).replace(/__PROTO__/g, proto);
  const files = [
    { name: 'README.md', data: readme({ name, motd, maxPlayers, port, edition }) },
    { name: 'start.sh', data: edition === 'java' ? START_JAVA : START_BEDROCK, mode: 0o755 },
    { name: 'stop.sh', data: STOP, mode: 0o755 },
    { name: 'watchdog.sh', data: WATCHDOG, mode: 0o755 },
    { name: 'iptables.rules', data: firewall, mode: 0o755 },
    { name: 'fail2ban-jail.conf', data: FAIL2BAN.replace(/__PORT__/g, String(port)).replace(/__PROTO__/g, proto) },
    { name: 'omlet-minecraft.service', data: SYSTEMD },
  ];
  if (edition === 'java') {
    files.push(
      { name: 'server.properties', data: javaProperties({ name, motd, maxPlayers, port }) },
      { name: 'whitelist.json', data: WHITELIST },
      { name: 'ops.json', data: '[]\n' },
      { name: 'eula.txt', data: '# Read and accept the Minecraft EULA, then set this to true.\neula=false\n' },
    );
  } else {
    files.push(
      { name: 'server.properties', data: bedrockProperties({ name, motd, maxPlayers, port }) },
      { name: 'allowlist.json', data: WHITELIST },
      { name: 'permissions.json', data: PERMISSIONS },
      { name: 'valid_known_packs.json', data: '[{"pack_id":"vanilla","version":"1.0.0"}]\n' },
    );
  }
  files.push({
    name: 'VERSION',
    data: `pack=1.0.0\nedition=${edition}\nmax_players=${maxPlayers}\nport=${port}\nserver_slots_cap=${config.minecraft.maxSlots}\n`,
  });
  return files;
}

module.exports = { build, bedrockProperties, javaProperties };
